namespace be_asa_shared_contracts.Enums
{
    public enum FunctionCode // thêm chức năng phía dưới cùng k làm đôi thứ tự
    {
        // Super admin

        ROLE_MANAGEMENT,
        FUNCTION_MANAGEMENT,
        COMMAND_MANAGEMENT,
        COMMANDINFUNCTION_MANAGEMENT,
        SUBSYSTEM_MANAGEMENT,
        PERMISSIONGROUPTYPE_MANAGEMENT,
        BRANCH_MANAGEMENT,
        USER_SETTING_MANAGEMENT,
        MODULE_MANAGEMENT,

        // Admin 
        PERMISSION_MANAGEMENT,
        PERMISSIONGROUP_MANAGEMENT,
        USERINBRANCH_MANAGEMENT,
        LOGGING_MANAGEMENT,
        TEMPLATE_MAIL_MANAGEMENT,
        MAIL_CONFIG_MANAGEMENT,
        SEND_MAIL_MANAGEMENT,

        // User

        //Menu
        CONFIG_AUTHENTICATION_MANAGEMENT,
        AUTHENTICATION_MANAGEMENT,
        FOODORDER_MANAGEMENT,
        HOTEL_MANAGEMENT,
        SETTING_MANAGEMENT,
        MAIL_MANAGEMENT,

        CUSTOMER_MANAGEMENT,
        CUSTOMER_LIST_MANAGEMENT,
        SYSTEM_SETTING_MANAGEMENT,
        JOB_MANAGEMENT,
        CRONJOB_MANAGEMET,
        CRONJOB_lOG_MANAGEMET
    }
}
